
after_script:
  - cd ./public
  - git init
  - git config user.name "your-git-name"
  - git config user.email "your-email-address"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master




# 指定构建环境是Node.js，当前版本是稳定版
language: node_js
node_js:
  - lts/*

# 设置钩子只检测master分支的push变动
branches:
  only:
    - master

# 设置缓存文件
cache:
  directories:
    - node_modules

#在构建之前安装hexo环境和主题，这里的主题就是原来修改过的主题，我将其托管到另一个github仓库，直接clone就行，否则每次都是新的主题，要重新设置。
before_install:
  - npm install -g hexo-cli

#安装git插件和搜索功能插件
install:
  - npm install
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-searchdb --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "aipikachu"
  - git config user.email "zhangwya@gmail.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  # - hexo deploy
  