# before_script:
#   - apt-get update -qq&&apt-get install -y -qq pandoc
# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: stable

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定博客的仓库地址
env:
 global:
   - GH_REF: github.com/aipikachu/aipikachu.github.io.git

# 指定博客源码分支，master.
branches:
  only:
    - master

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm uninstall hexo-renderer-pandoc --save
  - npm uninstall hexo-renderer-marked --save
  - npm install hexo-renderer-kramed --save
  - npm uninstall hexo-math --save
  - npm install hexo-renderer-mathjax --save
  - npm install hexo-abbrlink --save
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-feed --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - cd ./public
  - git init
  - git config user.name "Vincent Zhang"
  - git config user.email "zhangwya@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

